Story5/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

urlpatterns = [
	path('', jadwal_details_view, name="sched_overview"),
	path('create/', jadwal_create, name="create_event"),
	path('save/', jadwal_save, name="save_event"),
	path('delete-all/', delete_all_schedule, name="delete_all_event")
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
#from lab_1.views import index as index_lab1
from Story4.views import *
from Story5.views import *
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='index/')),
    path('index/', load_base_html, name='Story4-index'),
    path('schedule/', include(('Story5.urls', 'Story5'), namespace='Story5'))

    
]

Story4/models.py
from django.db import models


# Create your models here.

Story5/models.py
from django.db import models

class JadwalPribadi(models.Model):
	date = models.DateField()
	time = models.TimeField()
	event_name = models.CharField(max_length=32, blank=False)
	location = models.CharField(max_length=48)
	category = models.CharField(max_length=16)



# Create your models here.

Story4/forms.py
from django import forms
from django.conf import settings

Story5/forms.py
from django import forms
#from django.conf import settings

from .models import JadwalPribadi

class JadwalForm(forms.Form):
	date = forms.DateField(label='',
		required=True, 
		#input_formats=settings.DATE_INPUT_FORMATS,
		widget=forms.DateInput(attrs={'class' : 'input-group-text','id' : 'f_date', 'type':'date'}))#,'placeholder':'d/m/Y'})),
	time = forms.TimeField( label='',
		required=True,
		widget=forms.TimeInput(attrs={'class' : 'input-group-text','id' : 'f_time', 'type' : 'time'}))
	event_name = forms.CharField(label='',
		required=True,
		max_length=32,
		widget=forms.TextInput(attrs={'class' : 'input-group-text','id' : 'str_name', 'type':'text','placeholder':'Event\'s Name'}))
	location = forms.CharField(label='',
		max_length=48,
		required=False,
		widget=forms.TextInput(attrs={'class' : 'input-group-text','id' : 'str_loc', 'type':'text','placeholder':'Location'}))
	category = forms.CharField(label='',
		max_length=16,
		required=False,
		widget=forms.TextInput(attrs={'class' : 'input-group-text','id' : 'str_ctg', 'type':'text','placeholder':'Category'}))


	#class Meta:
	#	model = JadwalPribadi
	#	fields = [
	#		'event_name',
	#		'date',
	#		'time',
	#		'location',
	#		'category',
	#	]

			

Story4/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect


def load_base_html(request) :
    return render_to_response('base.html')

def index_view(request):
    project = Project.objects.all()
    response['project'] = project

    html = 'index.html'

    return render_to_response(request, html, response)





# Create your views here.

Story5/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .forms import JadwalForm

from .models import JadwalPribadi
# Create your views here.

response = {}
def jadwal_create(request):
	response['title'] = 'Add Event'
	response['request_data_jadwal'] = JadwalForm()
	return render(request, 'create_schedule.html', response)

def jadwal_save(request):
	form = JadwalForm(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['date'] = request.POST['date']	
		response['time'] = request.POST['time']
		response['event_name'] = request.POST['event_name']
		response['location'] = request.POST['location']
		response['category'] = request.POST['category']

		Jadwal_submit = JadwalPribadi(
			date=response['date'],
			time=response['time'],
			event_name=response['event_name'],
			location=response['location'], 
			category=response['category'],
			)

		Jadwal_submit.save()
		return HttpResponseRedirect('/schedule/')
	else : 	
		form = JadwalForm()
	return render(request, 'view_schedule.html')

def jadwal_details_view(request):
	schedules = JadwalPribadi.objects.all()
	response['schedules'] = schedules
	return render(request, "view_schedule.html", response)

def delete_all_schedule(request):
	JadwalPribadi.objects.all().delete()
	return HttpResponseRedirect('/schedule/')

Story4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap Core CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom CSS and font here-->
        <link href="static/css/style.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600i,800,900" rel="stylesheet" type="text/css">

    </head>

    <!--         NAVIGATION BAR SECTION               -->
    <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
                <a class="nav-textxx" href="/index/#intro">INTRO</a> <br/>
                <a class="nav-textxx" href="/index/#portfolio">PORTFOLIO</a> <br/>
                <a class="nav-textxx" href="/index/#gallery">GALLERY</a> <br/>
                <a class="nav-textxx" href="/index/#contact-me">CONTACT ME</a> <br/>
                <a class="nav-textxx" href="/schedule/">SCHEDULE</a> <br/>
                <br/>
                <a class="nav-textxx" href="#">REGISTER!</a> <br/>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </div>
    <body id="page-top" data-spy="scroll">


    {% block content %}
    {% include "index.html" %}
    {% endblock %}


    <!-- Bootstrap Core JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Custom Script -->
    <script src="{% static 'js/interactive.min.js' %}"}></script>
    <script>
        $(function() {
            $( "#id_date" ).datepicker({
                minDate: 0,
                maxDate: "+24M",
                yearRange: "1900:2025",
                // You can put more options here.
            });
        });
    </script>
    </body>
</html>

<!--#########################OLD HTML BELOW#################-->

Story4/templates/index.html
{% load static %}

{% block content %}

<div class="page-1" id="intro">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm"></div>
            <div class="col-md-6"><h1 class="big-text1xx"><strong>HELLO</strong></h1>
                <p class="desc-textxx">My name is Adam Maulana,<br/>
                    I’m from Indonesia and living in Jakarta.<br/>
                    I study in University of Indonesia, majoring in <br/> Information System.
                </p>
            </div>
            <div class="col-md">
                <img src="https://i.postimg.cc/P5t9GMtX/image.png" class="photo-background-a1" >
                <br/>
            </div>
            <div class="col-md"></div>

        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>
<div class="page-2" id="portfolio">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-2">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>SKILL</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-5">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>EXPERIENCE</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-2">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>ARTICLES</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-1"><br/></div>
        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>
<div class="page-3" id="gallery">
    <div class="container-fluid">
        <div class="row align-items-center">
            <br/><br/><br/><br/><br/><br/><br/><br/>
            <div class="col-sm-1"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-8"><h1 class="big-text2xx-dark"><strong>Capture of My Life</strong></h1></div>
            <div class="col-sm-1"></div>
            <div class="col-sm-1"></div>
            <br/><br/><br/><br/>

        </div>
        <div class="row">
            <div class="col"></div>
        </div>
        <div class="row align-items-center">
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/KYhdqyRW/lr_DSC3276.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/Wp9c2KHD/DSC3542.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/dtv6xtBr/image.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>

            <div class="col-sm-1"><br/></div>
        </div>
    </div>
</div>

<div class="page-4" id="contact-me">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm"></div>
            <div class="col-md-6"><h1 class="big-text1xx"><strong>Contact Me!</strong></h1>
                <br/><br/><br/><br/>
                <div class="row">
                    <div class="col-sm-2"><img src="https://image.flaticon.com/icons/svg/123/123734.svg" class="icon-xx"></div>
                    <div class="col-md-3"><p class="desc-textxx">@adamln</p></div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <img src="https://image.flaticon.com/icons/svg/61/61164.svg" class="icon-xx">
                    </div>
                    <div class="col-md-3"><p class="desc-textxx">@adam_mln</p></div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <img src="https://image.flaticon.com/icons/svg/732/732200.svg" class="icon-xx"></div>
                    <div class="col-md-3">
                        <p class="desc-textxx">adam.maulana2603@gmail.com</p>
                    </div>
                </div>
            </div>
            <div class="col-md">
            </div>
            <div class="col-md"></div>
        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>


{% endblock %}

Story5/templates/create_schedule.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}


{% block content %}

<a href="/schedule/" class="btn btn-primary btn-lg" role="button" aria-disabled="false">Back</a>

<form id="form" method="POST" action="{% url 'Story5:save_event' %}">
 	{% csrf_token %}

	{{ request_data_jadwal.as_p }}

	<input type='submit' value='Create!' class="btn btn-primary btn-lg"/>
</form>

{% endblock %}

Story5/templates/view_schedule.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}

{% block content %}

<body>
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-5"> 
                <a href="/schedule/create/" class="btn btn-primary btn-lg" role="button" aria-disabled="false">Create New Schedule!</a>
            </div>
            <div class="col-md-5"> 
                <form action="{% url 'Story5:delete_all_event' %}" method="GET">
                    <a href="delete/" class="btn btn-primary btn-lg" role="button" aria-disabled="false">Clear Event!</a>
            </div>
        </div>
        {% for data in schedules%}
        <!-- ===============individual schedule view start -->
        <div class="row">
        	<div class="alert alert-info" role="alert">
        		<div class="row">
        			<span class="badge badge-dark">
        				<a><Strong>{{ data.date | date:'l'}}</Strong></a><br/>
        				<a class="big-text1xx">{{ data.date | date:'d'}}</a><br/>
        				<a><strong>{{ data.date | date:'M Y'}}</strong></a>
        			</span>
        			<span class="badge badge-info">
        				<a class="desc-textxx">{{ data.event_name }}</a><br/><br/>
        				<a class="desc-textxx-small">Location : {{ data.location }}</a><br/>
        				<a class="desc-textxx-small">Category : {{ data.category }}</a><br/>
        				<a class="desc-textxx-small">Time : {{ data.time | time:'h:i A'}}</a>
        			</span>
        		</div>
        	</div>
           <!-- ==========individual schedule view end here -->
        </div>
        {% endfor %}
	</div>
</body>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap Core CSS-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom CSS and font here-->
        <!--<link href="static/css/style.css" rel="stylesheet">-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600i,800,900" rel="stylesheet" type="text/css">
        <title>Hey, It's Adam</title>

    </head>

    <!--         NAVIGATION BAR SECTION               -->
    <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
                <a class="nav-textxx" href="/index/#intro" name="introNav">INTRO</a> <br/>
                <a class="nav-textxx" href="/index/#portfolio" name="portoNav">PORTFOLIO</a> <br/>
                <a class="nav-textxx" href="/index/#gallery" name="galleryNav">GALLERY</a> <br/>
                <a class="nav-textxx" href="/index/#contact-me" name="contactNav">CONTACT ME</a> <br/>
                <a class="nav-textxx" href="/schedule/" name="schedNav">SCHEDULE</a> <br/>
                <br/>
                <a class="nav-textxx" href="#">REGISTER!</a> <br/>
            </div>
        </div>
        <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" name="navbarButton">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </div>
    <body id="page-top" data-spy="scroll">


    {% block content %}
    {% include "index.html" %}
    {% endblock %}



    <!-- Bootstrap Core JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Custom Script -->
    <script src="{% static 'js/interactive.min.js' %}"}></script>
    </body>
</html>

<!--#########################OLD HTML BELOW#################-->

templates/index.html
{% load static %}

{% block content %}

<div class="page-1" id="intro">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm"></div>
            <div class="col-md-6"><h1 class="big-text1xx"><strong>HELLO</strong></h1>
                <p class="desc-textxx">My name is Adam Maulana,<br/>
                    I’m from Indonesia and living in Jakarta.<br/>
                    I study in University of Indonesia, majoring in <br/> Information System.
                </p>
            </div>
            <div class="col-md">
                <img src="https://i.postimg.cc/P5t9GMtX/image.png" class="photo-background-a1" >
                <br/>
            </div>
            <div class="col-md"></div>

        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>
<div class="page-2" id="portfolio">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-2">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>SKILL</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-5">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>EXPERIENCE</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-2">
                <blockquote class="blockquote text-center">
                    <a class="semi-big-textxx"><strong>ARTICLES</strong></a>
                </blockquote>
            </div>
            <div class="col-sm-1"><br/></div>
        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>
<div class="page-3" id="gallery">
    <div class="container-fluid">
        <div class="row align-items-center">
            <br/><br/><br/><br/><br/><br/><br/><br/>
            <div class="col-sm-1"></div>
            <div class="col-sm-2"></div>
            <div class="col-sm-8"><h1 class="big-text2xx-dark"><strong>Capture of My Life</strong></h1></div>
            <div class="col-sm-1"></div>
            <div class="col-sm-1"></div>
            <br/><br/><br/><br/>

        </div>
        <div class="row">
            <div class="col"></div>
        </div>
        <div class="row align-items-center">
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-1"><br/></div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/KYhdqyRW/lr_DSC3276.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/Wp9c2KHD/DSC3542.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>
            <div class="col-sm-3">
                <img src="https://i.postimg.cc/dtv6xtBr/image.jpg" class="img-thumbnail" alt="Author : Adam">
            </div>

            <div class="col-sm-1"><br/></div>
        </div>
    </div>
</div>

<div class="page-4" id="contact-me">
    <div class="container-fluid">
        <div class="row">
            <br/>
        </div>
        <div class="row">
            <div class="col"></div>
            <br/>
        </div>
        <div class="row align-items-center">
            <div class="col-sm"></div>
            <div class="col-md-6"><h1 class="big-text1xx"><strong>Contact Me!</strong></h1>
                <br/><br/><br/><br/>
                <div class="row">
                    <div class="col-sm-2"><img src="https://image.flaticon.com/icons/svg/123/123734.svg" class="icon-xx"></div>
                    <div class="col-md-3"><p class="desc-textxx">@adamln</p></div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <img src="https://image.flaticon.com/icons/svg/61/61164.svg" class="icon-xx">
                    </div>
                    <div class="col-md-3"><p class="desc-textxx">@adam_mln</p></div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <img src="https://image.flaticon.com/icons/svg/732/732200.svg" class="icon-xx"></div>
                    <div class="col-md-3">
                        <p class="desc-textxx">adam.maulana2603@gmail.com</p>
                    </div>
                </div>
            </div>
            <div class="col-md">
            </div>
            <div class="col-md"></div>
        </div>
        <div class="row">
            <div class="col-sm"></div>
        </div>
    </div>
</div>


{% endblock %}